### ISSUE TITLE
扩展完全没用

### ISSUE THREAD

**Issue by lyf1134** [monkeyWie/bilibili-helper#2]
win10 chrome70
没有pd下载按钮
直连下载解析的文件名是乱码
一直未知，然后失败
没有error日志

**Comment by shenthought** [comment]
@lyf1134 测试了下，要换回旧版哔哩哔哩，并且要切换代理的情况下才会出现“PD下载”。
@monkeyWie 请大大适配新版哔哩哔哩播放器，修复下文件名乱码的bug

**Comment by monkeyWie** [comment]
@shenthought 0.13版本已经支持新版本播放器
